name: Deploy to GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build website
      env:
        # Optional base url set in repo secrets e.g. /rchain-docs/
        # Workaround for https://github.com/facebook/docusaurus/issues/448
        BASE_URL: ${{ secrets.BASE_URL }}
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
